# Generated by Django 4.2.25 on 2025-10-08 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSubnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cidr', models.CharField(help_text='e.g. 192.168.1.0/24 or 2001:db8::/48', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('auto', 'Auto Detect'), ('v4_to_v6_mapped', 'IPv4 → IPv6 (mapped ::ffff)'), ('v4_to_6to4', 'IPv4 → IPv6 (6to4 2002::/16)'), ('v6_mapped_to_v4', 'IPv6 (mapped) → IPv4'), ('expand_v6', 'Expand IPv6'), ('compress_v6', 'Compress IPv6'), ('subnet_info', 'Subnet Info'), ('reverse_dns', 'Reverse DNS'), ('eui64', 'EUI-64 from MAC')], default='auto', max_length=40)),
                ('input_text', models.CharField(max_length=255)),
                ('result_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
